test:
 adapter: mysql2
 encoding: utf8
 database: myapp_test
 username: root
 password: root
development:
  adapter: mysql2
  encoding: utf8
  database: ebo_db
  username: root
  password: root
production:
  adapter: postgresql
  encoding: unicode
  database: ebo-test
  pool: 5
  username: postgres
  password: password